name: Docker Build and Deploy

on:
  push:
    branches: [main]  # 触发分支

env:
  DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}  # 镜像名称（如：vue-app）
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}  # 镜像仓库（可选：阿里云ACR、腾讯云TCR等）
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  # 仓库用户名（GitHub Secrets）
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  # 仓库密码（GitHub Secrets）
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # 云服务器SSH私钥（GitHub Secrets）
  ECS_SERVER_IP: ${{ secrets.ECS_SERVER_IP }}      # 云服务器IP（GitHub Secrets）

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Alibaba Cloud Registry
        run: |
          docker login --username=$DOCKER_USERNAME $DOCKER_REGISTRY -p $DOCKER_PASSWORD

      - name: Build Docker Image
        run: |
          docker build -t $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:latest .

      - name: Tag Docker Image
        run: |
          docker tag $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:latest $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:latest

      - name: Push Docker Image
        run: |
          docker push $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:latest

      - name: Deploy to Cloud Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.ECS_SERVER_IP }}
          username: root
          password: ${{ secrets.ECS_SERVER_PASSWORD }}
          script: |
            docker login --username=${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_REGISTRY }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest
            if [ $(docker ps -q -f name=vue-app) ]; then docker stop vue-app; fi
            if [ $(docker ps -a -q -f name=vue-app) ]; then docker rm vue-app; fi
            docker run -d --name vue-app -p 80:80 ${{ secrets.DOCKER_REGISTRY }}/$DOCKER_IMAGE_NAME:latest