name: Docker Build and Deploy

on:
  push:
    branches: [main]  # 触发分支

env:
  DOCKER_IMAGE_NAME: vue-app  # 镜像名称（如：vue-app）
  DOCKER_REGISTRY: ${{ secrets.DOCKER_USERNAME }}  # 镜像仓库（可选：阿里云ACR、腾讯云TCR等）
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  # 仓库用户名（GitHub Secrets）
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  # 仓库密码（GitHub Secrets）
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # 云服务器SSH私钥（GitHub Secrets）
  SERVER_IP: ${{ secrets.SERVER_IP }}        # 云服务器IP（GitHub Secrets）

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Registry
        run: |
          echo "$DOCKER_PASSWORD" | docker login $DOCKER_REGISTRY -u $DOCKER_USERNAME --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t $DOCKER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE_NAME:latest .

      - name: Push Docker Image
        run: |
          docker push $DOCKER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE_NAME:latest

      - name: Deploy to Cloud Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull $DOCKER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE_NAME:latest
            docker stop vue-app || true
            docker rm vue-app || true
            docker run -d --name vue-app -p 80:80 $DOCKER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE_NAME:latest